runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /(img|css|fonts|js|bower_components|ang)/(.*)
  static_files: static/\1/\2
  upload: static/(img|css|fonts|js|bower_components|ang)/(.*)
  secure: always
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: ssl
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.py[co]$
- ^node_modules\/
- ^node_modules(/.*)?
- .*node_modules 
- ^bower_components\/
