main:
    jwt_secret: '1secretthing'
general:
    plugin_dir: cd_plugins
plugins:
    tfa_service:
        module: tfa_service
        model: tfa_record
        user_field: tfa_verified
        routes: maybe not needed
users:
    user_types:
        - dm
        - ms
    signup_args:
        - email
        - firstname
        - lastname
        - password
        - userType
    key_arg: email
    validators:
        - tfa_service
    recorders: []
    testing:
        testers:
            - email: dm1@ce.pbi
              firstname: dave
              lastname: matter
              password: pass
              userType: dm
            - email: dm2@ce.pbi
              firstname: dave
              lastname: matter
              password: pass
              userType: dm
        keys_to_remove: 
            - firstname
            - lastname
            - email




